markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /:categories/:year/:month/:day/:title/

#self defination
excerpt_separator: "\n"
paginate: 10
#self end

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1

repository: https://github.com/jekyll/jekyll
help_url: https://github.com/jekyll/jekyll-help

collections:
  docs:
    output: true
